### ISSUE TITLE
vSphere host snapshot feature in foreman

### ISSUE THREAD

**Issue by nagarjuna** [fog/fog-vsphere#12]
Hi,

I am trying to implement snapshot feature for host in VMware compute resource. So this plugin will provide create/list/delete/restore snapshot of host in foreman. Will you please provide documentation on fog-vsphere gem to implement this plugin? 

like methods to call to create/list/delete/restore snapshot using fog-vsphere gem

**Comment by jrgarcia** [comment]
@nagarjuna Are you just looking for documentation on how to use the gem? If so, I'll see what I can do for this. I inherited this codebase so I'm not too incredibly familiar with it, but I'll do what I can in the coming weeks.

**Comment by jrgarcia** [comment]
@nagarjuna I'm going to close this for now, but I do plan on adding a lot more documentation for this. I realize there is a severe lack of documentation and I'd really like to fix that.
