### ISSUE TITLE
Unable to provision VMs in ESXi with no DRS

### ISSUE THREAD

**Issue by rfrht** [fog/fog-vsphere#125]
We're trying to provision a VM in a VMWare site with no DRS (DRS is a premium feature, this is a standard product), and it fails with the error:

2018-03-06 14:15:49 5c9e05ec [app] [W] Failed to create a compute ESX (VMware) instance test.example.com: SystemError: vim.fault.StorageDrsDisabledOnVm

Questions:

1. Is DRS required to run this module?
1.1 If true, why?
2. Else; can we please fix the code to let it run without DRS?

Thanks!

**Comment by chris1984** [comment]
Hi @rfrht im working on your case at Red Hat and will take this on since im working with you

**Comment by timogoebel** [comment]
Do you guys use "clone from template" or "pxe based provisiong" to set up the VM?

**Comment by rfrht** [comment]
I'm closing this issue - Actually we were able to make it work by choosing the right options :-)
-NOTABUG
