### ISSUE TITLE
can't assign networking/datastore after upgrding to Vsphere 6.5

### ISSUE THREAD

**Issue by bp85** [fog/fog-vsphere#128]
Hi,

we're using fog-vsphere 1.9.2
After upgrading to Vsphere6.5 we're having difficulties creating new VMs via foreman
Initially we can't able to select the datacenter, but now after selecting the datacenter, I can't able to assign a network/ cannot create VM from foreman
I can create VM if I login to VSphere and assign proper network
I can list all the existing VMs in that datacenter, but can't see the status of datacenter 
related issue https://github.com/vmware/rbvmomi/issues/133

Error on interfaces section in foreman:
`Error loading interfaces information: Internal Server Error`

Error in Virtual Machine section
`Failure: NoPermission: `

Any help would be appreciated
Thanks in advance

**Comment by bp85** [comment]
can someone acknowledge this issue?

**Comment by bp85** [comment]
I haven't collected the debug logs, but certainly can 
Let me know which exact logs you want

**Comment by chris1984** [comment]
@bp85 can you get me the /var/log/foreman/production.log please.

**Comment by bp85** [comment]
@chris1984 I sent you foreman production log via email, let me know if you haven't received

**Comment by chris1984** [comment]
@bp85 I see this in the production.log

~~~
 | /usr/share/foreman/app/services/compute_resource_cache.rb:68:in `instance_eval'
 | /usr/share/foreman/app/services/compute_resource_cache.rb:68:in `get_uncached_value'
 | /usr/share/foreman/app/services/compute_resource_cache.rb:22:in `cache'
~~~

Are you using caching? Can I have you try the following and let me know the result:

~~~
 # foreman-rake console
   > ComputeResource.find_by(:name => 'superman').refresh_cache              // change 'superman' to the name of your compute resource
~~~

**Comment by bp85** [comment]
@chris1984 I think chachig is enabled for VMware, but can be turned off 
```
irb(main):001:0> ComputeResource.find_by(:name => 'VMware').refresh_cache
=> true
```

**Comment by chris1984** [comment]
@bp85 Can you try this and see if it helps:

~~~
ComputeResource.find_by(:name => 'name').refresh_cache
~~~

**Comment by bp85** [comment]
@chris1984 , let me take a step back here and explain so that you have an idea of what happened here
Everything worked fine ( create VM through foreman) until a month ago, our Infrastructure team upgraded VMware Vsphere server to 6.5 from 5.5, after that the connection between Vsphere and foreman broken, Then I deleted compute resource(VMware) and re-created , Then I ran into an issue where in api When I try to load datacenter it show a meesage "Success: Test connection was successful" but no datacenters listed.
At this point I'm unable to see already existing VMs in foreman.
Then I opened https://github.com/vmware/rbvmomi/issues/133 and found that `overallStatus` is not printing
so, I commented out https://github.com/fog/fog-vsphere/blob/master/lib/fog/vsphere/requests/compute/list_datacenters.rb#L11 on foreman server and reloaded foreman service
Then in api, I'm able to select the correct datacenter and I can see all VMs in that datacenter
where as I ran into an issue with network and VM creation part as described [above](https://github.com/fog/fog-vsphere/issues/128#issue-305665771) 

FYI, I tried to refresh cache on VMware, that didn't helped and now I disabled caching on  VMware resource.

**Comment by bp85** [comment]
@chris1984 any thoughts ?

**Comment by chris1984** [comment]
@bp85 Hi sorry for the delay, a few things came up. I will start looking at this Monday again for you.

**Comment by bp85** [comment]
@chris1984 Thanks, Let me know if you need anything from me

**Comment by chris1984** [comment]
@timogoebel do you have any suggestions on this one? I am still trying a few things here and might need to set up a reproducer since I am unable to replicate it from 6.2 > 6.3

**Comment by timogoebel** [comment]
@bp85: `No permission` errors from vSphere are usually just that: The user that you're using to access vSphere API does not have the required permissions.

To check that, you can access your vCenter directly by browsing to `https://your.vcenter.example.com/mob/?moid=group-d1`. Please login with the same credentials you are using in Foreman/Satellite. You should be able to navigate to your datacenter object by clicking on the link in the row marked with `childEntity`:

![image](https://user-images.githubusercontent.com/4107560/38516703-2569bc7e-3c38-11e8-8d4d-c118e0ef7774.png)

**Comment by bp85** [comment]
@timogoebel as I can see, there is no permission issue
<img width="1628" alt="screen shot 2018-04-09 at 3 40 26 pm" src="https://user-images.githubusercontent.com/17888860/38519161-e7c3af9a-3c0c-11e8-93dc-3a996c68712c.png">
<img width="1657" alt="screen shot 2018-04-09 at 3 39 52 pm" src="https://user-images.githubusercontent.com/17888860/38519162-e7d13d18-3c0c-11e8-960d-68a7806ad7bf.png">

**Comment by chris1984** [comment]
@bp85 do you think I could get your configs/database to try to test it here. I have not had luck getting it to replicate. Also for the role that Foreman/Fog is using can I have you run this powercli and update the ticket:

Get-VIPermission | Where {$_.Role –eq “Admin”} | Select Role, Principal, Entity, UI

**Comment by chris1984** [comment]
@bp85 Are you running just Foreman or Katello too?

**Comment by bp85** [comment]
@chris1984 Just foreman

**Comment by chris1984** [comment]
@bp85 can I get a copy of your configs and dbs by doing the following:

https://theforeman.org/manuals/1.16/index.html#5.5.1Backup

**Comment by bp85** [comment]
@chris1984 I sent you configs & DB, let me know if you haven't received them

**Comment by chris1984** [comment]
@bp85 I got the sql/configs, I will start working on looking at this.

**Comment by bp85** [comment]
@chris1984 Thanks, we're using foreman-1.15.6 and vSphere 6.5 on VMware

**Comment by chris1984** [comment]
@bp85 Hi I was not able to recreate the issue here, let me know if I missed something, I made a recording here with the steps I did:

https://drive.google.com/file/d/1qKJVghYG-QX7digkh4EqfP4BkrpFTMCB/view?usp=sharing

**Comment by bp85** [comment]
@chris1984 , You're right the issue is not from foreman side, it is from vsphere.
After adding read only permissions to the vsphere server for foreman user, I was able to provision new vms  from foreman
I guess it is changed from 5.5 -> 6.5
Feel free to close this issue and Thanks for all your help in debugging this

**Comment by timogoebel** [comment]
Thanks, guys.
