### ISSUE TITLE
 Required property diskId is missing from data object of type VirtualMachineRelocateSpecDiskLocator

### ISSUE THREAD

**Issue by timogoebel** [fog/fog-vsphere#132]
Cloned from: https://projects.theforeman.org/issues/21520

VM cloning fails with since v1.13.0:

```
2017-10-31T18:08:44 f00149dd [app] [W] Failed to create a compute vpshere (VMware) instance foo.example.com: InvalidRequest:
 | Required property diskId is missing from data object of type VirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec.DiskLocator
 | at line 1, column 507
 |
 | while parsing property "disk" of static type ArrayOfVirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec
 | at line 1, column 359
 |
 | while parsing property "location" of static type VirtualMachineRelocateSpec
 |
 | while parsing serialized DataObject of type vim.vm.CloneSpec
 | at line 1, column 318
 |
 | while parsing call information for method CloneVM_Task
 | at line 1, column 177
 |
 | while parsing SOAP body
 | at line 1, column 167
 |
 | while parsing SOAP envelope
 | at line 1, column 0
 |
 | while parsing HTTP request for method clone
 | on object of type vim.VirtualMachine
 | at line 1, column 0
 |
 | RbVmomi::Fault: InvalidRequest:
 | Required property diskId is missing from data object of type VirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec.DiskLocator
 | at line 1, column 507
 |
 | while parsing property "disk" of static type ArrayOfVirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec
 | at line 1, column 359
 |
 | while parsing property "location" of static type VirtualMachineRelocateSpec
 |
 | while parsing serialized DataObject of type vim.vm.CloneSpec
 | at line 1, column 318
 |
 | while parsing call information for method CloneVM_Task
 | at line 1, column 177
 |
 | while parsing SOAP body
 | at line 1, column 167
 |
 | while parsing SOAP envelope
 | at line 1, column 0
 |
 | while parsing HTTP request for method clone
 | on object of type vim.VirtualMachine
 | at line 1, column 0
 | /usr/share/foreman/vendor/ruby/2.1.0/gems/rbvmomi-1.11.3/lib/rbvmomi/connection.rb:63:in `parse_response'
 | /usr/share/foreman/vendor/ruby/2.1.0/gems/rbvmomi-1.11.3/lib/rbvmomi/connection.rb:92:in `call'
 | /usr/share/foreman/vendor/ruby/2.1.0/gems/rbvmomi-1.11.3/lib/rbvmomi/basic_types.rb:213:in `_call'
 | /usr/share/foreman/vendor/ruby/2.1.0/gems/rbvmomi-1.11.3/lib/rbvmomi/basic_types.rb:76:in `block (2 levels) in init'
 | /usr/share/foreman/vendor/ruby/2.1.0/gems/fog-vsphere-1.13.1/lib/fog/vsphere/requests/compute/vm_clone.rb:678:in `vm_clone'
```

This was intoduced by b182db835e34af17ea43acc2029509a161104cef.

@scambra: Do you have any pointers how to fix this?

**Comment by scambra** [comment]
Is it hapenning when cloning and adding new disks?
I have this code when I clone a vm:

```ruby
    vol = server.volumes[index] || server.volumes.new
    vol.size_gb = size
    vol.datastore = datastore_name
    if vol.key.nil?
      server.volumes << vol
      vol.server = server
      vol.controller_key = server.volumes[0].controller_key
      vol.set_unit_number
    end
    vol
```

server is the vm to be cloned, and this code is a method I call for each volume, to setup volumes before calling server.clone
vol.key is nil for new volumes, then I add volume to server.volumes, set vol.server and controller_key because calling set_unit_number needs it.

**Comment by kartikaydw** [comment]
Hey @chris1984 @scambra 

I am getting below error while attaching the disk. Any Pointers?

**Required property id is missing from data object of type ID

while parsing serialized DataObject of type vim.vslm.ID
at line 1, column 255

while parsing call information for method AttachDisk_Task
at line 1, column 177

while parsing SOAP body
at line 1, column 167

while parsing SOAP envelope
at line 1, column 0

while parsing HTTP request for method attachDisk
on object of type vim.VirtualMachine
at line 1, column 0**

Code snippet.

 vm.AttachDisk_Task(
    diskId: did,
    datastore: vmdk_datastore,
    controllerKey: 1000,
    unitNumber: 14,

)

**Comment by chris1984** [comment]
@kartikaydw Are you using this with foreman or just the script alone?

**Comment by ezr-ondrej** [comment]
Hi, where have you took the code snipet?
It seems you are using directly the `rbvmomi` object. In such case I would suggest consulting a vSphere API documentation. Worth checking `did` is a number ;)

**Comment by kartikaydw** [comment]
Hey @chris1984 @ezr-ondrej , Thanks for your quick responses. 

Yes I am using this in rbvmomi script where I am using vStorageObjectManager to created disk and then AttachDisk_Task to attach the created disk. To diskId parameter is causing issues from inside the script whereas when I pass the same diskId through MOB the disk gets attached.

for better reference, below is snippet to create a disk and pry output

[1] pry(main)> vdisk
=> VStorageObject(
  config: VStorageObjectConfigInfo(
    backing: BaseConfigInfoDiskFileBackingInfo(
      datastore: Datastore("datastore-9082"),
      filePath: "[vnx-lun-1092] devops100.testdomain.com/8b692cf1996b4fa79582d81af13bbbfe.vmdk",
      provisioningType: "thin"
    ),
    capacityInMB: 1024,
    consumerId: [],
    consumptionType: ["disk"],
    createTime: 2019-07-31 18:14:29 UTC,
    id: ID( id: "0d469112-0d24-4ef9-ab60-cb594788dd14" ),
    iofilter: [],
    name: "[vnx-lun-12] devops100.testdomain.com%2fdevops100.testdomain.com_491.vmdk"
  )
)
[2] pry(main)>
[2] pry(main)> did
=> "0d469112-0d24-4ef9-ab60-cb594788dd14"
[3] pry(main)> did.class
=> String
[4] pry(main)>

=================================
vmdk_spec = RbVmomi::VIM::VslmCreateSpecDiskFileBackingSpec(
        datastore: vmdk_datastore,
        provisioningType: 'thin',
        path: "#{vmname}"
      )

      vmdk_backing = RbVmomi::VIM::VslmCreateSpec(
        capacityInMB: size.to_i * 1024,
        backingSpec: vmdk_spec,
        name: "[#{vmdk_datastore.name}] #{vmdk_file_name}",
       )

      vdisk = vim.serviceContent.vStorageObjectManager.CreateDisk_Task(
             spec: vmdk_backing,
      ).wait_for_completion

      res = vdisk.to_json
      did = JSON.parse(res)['config']['id']['id']
      puts did
     binding.pry

     vm.AttachDisk_Task(
        diskId: "d310bf94-e40b-499b-a7c6-b930c981fd35",
        datastore: vmdk_datastore,
        controllerKey: 1000,
        unitNumber: 14,
)

**Comment by ezr-ondrej** [comment]
Hi, I really believe you should open the issue in `rbvmomi`, but I have given fast look at the docs, you should use a`diskId: {id: did}` - nest it further :)

**Comment by kartikaydw** [comment]
Hi @ezr-ondrej , 
Thank you soooooo much, this works. It was driving me crazy and I was not able to find any reference.
Thanks a lot for looking into this and providing a working solution.
