### ISSUE TITLE
RbVmomi::Fault: InvalidProperty when retrieving collection or individual virtual machines

### ISSUE THREAD

**Issue by vhladama** [fog/fog-vsphere#2]
Exception:
```
RbVmomi::Fault: InvalidProperty:
from /gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:61:in `parse_response'
```

Stacktrace:
```
0: $GEM_HOME/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:61:in `parse_response'
1: $GEM_HOME/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:90:in `call'
2: $GEM_HOME/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:205:in `_call'
3: $GEM_HOME/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
4: $GEM_HOME/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/PropertyCollector.rb:20:in `collectMultiple'
5: $GEM_HOME/gems/fog-vsphere-0.1.1/lib/fog/vsphere/compute.rb:131:in `convert_vm_view_to_attr_hash'
6: $GEM_HOME/gems/fog-vsphere-0.1.1/lib/fog/vsphere/requests/compute/list_virtual_machines.rb:34:in `list_all_virtual_machines'
7: $GEM_HOME/gems/fog-vsphere-0.1.1/lib/fog/vsphere/requests/compute/list_virtual_machines.rb:16:in `list_virtual_machines'
8: $GEM_HOME/gems/fog-vsphere-0.1.1/lib/fog/vsphere/models/compute/servers.rb:25:in `all'
9: $GEM_HOME/gems/fog-core-1.32.1/lib/fog/core/collection.rb:113:in `lazy_load'
```

Environment:
```
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
rubygems 2.4.8

fog-core (1.32.1)
fog-vsphere (0.1.1)
rbvmomi (1.8.2)
```

Replication code:
```ruby
require 'fog/vsphere'

config = {
  provider: 'vsphere',
  vsphere_ssl: true,
  vsphere_rev: '4.0', # also fails using 4.1
  vsphere_username: 'xxx',
  vsphere_password: 'yyy',
  vsphere_server: 'zzz',
  vsphere_expected_pubkey_hash: 'hash'
}

connection = Fog::Compute.new(config)
dc = connection.datacenters.first
dc.virtual_machines.first
```

To figure out which attrs where causing errors, use the replication code above, but replace the last line with the following:

```ruby
original_map = Fog::Compute::Vsphere::Shared::ATTR_TO_PROP.dup

original_map.inject([]) do |memo, (key, value)|
  # change default mapping to load only one attr
  Fog::Compute::Vsphere::Shared::ATTR_TO_PROP = { key => value }
  begin
    dc.virtual_machines.first
  rescue RbVmomi::Fault
    memo << [key, value]
  end
  memo
end
```

result:
`[[:corespersocket, "config.hardware.numCoresPerSocket"], [:firmware, "config.firmware"]]`

Even though RbVmomi is raising the error, I don't think it's necessarily RbVmomi's fault, as the list off attrs that we're asking for is specified by Fog-vSphere.

If I'm using any incorrect or incompatible versions here or can provide any additional information, please let me know.  If you can give me a little guidance, I'm happy to open a PR that tries to wrap the prop mapping in some exception handling, or defines the ATTR_TO_PROP list more dynamically based on some condition... I just don't know what that might be.

**Comment by plribeiro3000** [comment]
@vhladama You think thats this list of attributes is wrong?

**Comment by jrgarcia** [comment]
@vhladama We just tried it in a lab environment here and had no issues. However, the only instance of vSphere I have access to at the moment is 5.5.0u2e. I specified `vsphere_rev: '4.0'` and `vsphere_rev: '4.1'`, but I'm not sure if that is enough to replicate the issue.

**Comment by vhladama** [comment]
Is there any way we can query the connected vsphere host to get more detailed version info? Api revision number or other version info? Or do I need to connect to the console to discover that?

**Comment by jrgarcia** [comment]
@vhladama I couldn't find a way to do that. I had to connect to vSphere to get that info.

**Comment by jrgarcia** [comment]
@vhladama Is this issue still occurring with the latest version? I'd like to fix this if it's still a problem for you, otherwise it would be nice to close this out.

**Comment by vhladama** [comment]
Sorry, @jrgarcia 

We stopped using the tool for a while.  We may pick it up again at a later point.

**Comment by jrgarcia** [comment]
No problem! Just let me know if you need any help.
