### ISSUE TITLE
Cloning a VM does not enable NIC at startup

### ISSUE THREAD

**Issue by drz9** [fog/fog-vsphere#250]
When I am cloning a VM (image based Foreman provisioning) the NIC is not connected at startup.
In the new VMs .vmx-File it is explicitely stated as: ethernet0.startConnected = "FALSE"
The template itself has not set this key.

**Comment by drz9** [comment]
Cloning does work and enable the interface. Issue is on Windows sysprep and Ipv6 setting which causes the issue when VMware Tools are doing Guest Customization

**Comment by chris1984** [comment]
Thanks for following up on this @drz9 sorry I didnt get to it
