### ISSUE TITLE
rbvmomi is deprecated

### ISSUE THREAD

**Issue by ekohl** [fog/fog-vsphere#279]
The repository is archived (https://github.com/vmware-archive/rbvmomi). Additionally the replacement (based on the new REST API) is also archived (https://github.com/vmware-archive/vsphere-automation-sdk-ruby).

This gem depends on it for basically all its functionality so I wonder what the path forward is.

**Comment by ekohl** [comment]
Someone pointed out there is a [rbvmomi2](https://github.com/ManageIQ/rbvmomi2) fork. That may be the easiest path forward.

**Comment by micwoj92** [comment]
This should be closed now.

**Comment by ekohl** [comment]
You're right, https://github.com/fog/fog-vsphere/pull/281 was merged already but wasn't linked.
