### ISSUE TITLE
Gem 3.6.1 on rubygems is broken/empty.

### ISSUE THREAD

**Issue by micwoj92** [fog/fog-vsphere#286]
Contains no data.
![image](https://github.com/fog/fog-vsphere/assets/45581170/ee9af843-89cc-4eac-8af8-311de41f2b25)

**Comment by chris1984** [comment]
Will get a new gem made by end of day tomorrow.

**Comment by chris1984** [comment]
New gem (correct size) 3.6.2 is published on rubygems.org, sorry for the trouble. Not sure what happened.
