### ISSUE TITLE
Version in tag 3.6.2 is 3.6.1 instead of 3.6.2

### ISSUE THREAD

**Issue by nadjaheitmann** [fog/fog-vsphere#289]
See here https://github.com/fog/fog-vsphere/blob/v3.6.2/lib/fog/vsphere/version.rb

**Comment by nadjaheitmann** [comment]
And tag 3.6.1 should be called v3.6.1 to be in line with the other tags :)

**Comment by chris1984** [comment]
I will start to take a look

**Comment by micwoj92** [comment]
@nadjaheitmann this is because 3.6.1 was broken on rubygems https://github.com/fog/fog-vsphere/issues/286

It was removed, 3.6.2 was uploaded and I guess that Chris just forgot to update ver before pushing.

Anyway I guess this is now "solved" due to 3.6.3 release.

**Comment by chris1984** [comment]
Yeah sorry about not coming back to this, 3.6.3 is released on rubygems.org and also if you use `fog-vsphere` in Foreman, it has been introduced into the nightly repos.

**Comment by chris1984** [comment]
@nadjaheitmann just made the PR there:

https://github.com/theforeman/foreman-packaging/pull/10308
