### ISSUE TITLE
tools_installed? returns true when the tools are not installed

### ISSUE THREAD

**Issue by jfhutchi** [fog/fog-vsphere#30]
def tools_installed?
     tools_state != "toolsNotInstalled"
 end

I am using vSphere 5.5 when I return the server object the hash states
 tools_version="guestToolsNotInstalled",
this would never return that they are not installed....

**Comment by jfhutchi** [comment]
tools_state="toolsNotRunning",
    tools_version="guestToolsNotInstalled",

**Comment by jrgarcia** [comment]
@jfhutchi I'll take a look at this as soon as I get a chance today

**Comment by jrgarcia** [comment]
@jfhutchi See if the release of [v0.6.2](https://rubygems.org/gems/fog-vsphere/versions/0.6.2) fixes this for you.

**Comment by jfhutchi** [comment]
Thanks, I'll test it asap!

**Comment by jfhutchi** [comment]
<Fog::Compute::Vsphere::Server
    id="50143d18-69b6-cad5-3b2f-8bb0a31b0471",
    name="cobalt-vm-win1",
    uuid="421495c7-dada-4c9d-b16f-8a17948b5d09",
    hostname=nil,
    operatingsystem=nil,
    public_ip_address=nil,
    power_state="poweredOn",
    tools_state="toolsNotRunning",
    tools_version="guestToolsNotInstalled",


2.2.2 :011 > vm.tools_installed?
 => true 

After installing 0.6.2 I still see the same result.. 
compute_service = Fog::Compute.new(provider: :vsphere,
                                            vsphere_password: @cred[:password],
                                            vsphere_username: @cred[:username],
                                            vsphere_server: @vmware_ip
                                           )
then I get vm by passing its' id to compute_service.servers.get id
Is this not the right way?

**Comment by jrgarcia** [comment]
@jfhutchi Yeah, that was a ridiculous mistake on my part. Sorry about that. Let me fix it.

**Comment by jfhutchi** [comment]
What was?

**Comment by jrgarcia** [comment]
e60519b returns based on that `||`. If the first side is `true` (which it is in the case you've mentioned), the entire statement is `true` regardless of the second half. I'm fixing it right now and writing tests for the various cases. I'll cut a new release fixing this shortly.

**Comment by jrgarcia** [comment]
@jfhutchi Try v0.6.3. This should fix the issue for you. Sorry again for the premature release.

**Comment by jfhutchi** [comment]
@jrgarcia Works like a charm! Thanks you for the quick turn around!!
