### ISSUE TITLE
Can't get hypervisor withoug running VM

### ISSUE THREAD

**Issue by yehlo** [fog/fog-vsphere#33]
We want to monitor all hypervisors in our firm, to achieve that we have a script which proceeds all the informationen we need. I need to get the hostnames of the hypervisors. I'm doing the following to get the hypervisors: 

```
hypervisors = []
client = ::Fog::Compute.new(
  :provider                             => 'vsphere',
  :vsphere_username                     => user,
  :vsphere_password                     => password,
  :vsphere_server                       => server,
  :vsphere_expected_pubkey_hash         => key
)
client.servers.each{|server| hypervisors << server.hypervisor}
```
through this I get a list with all hypervisors, with a running vm. But since we also need the failover devices we have an uncomplete list. 

To check if fog even realises if there are enough devices I did the following: 

```
num_of_hosts = 0

client.datacenters.each do |datacenter|
  datacenter.clusters.each do |cluster|
    num_of_hosts += cluster.num_host
  end
end
```

If I put out the variable `num_of_hosts` I get the amount of hypervisors overall.

Is there a way, to get all the hypervisor hostnames even if they don't have a running VM? 

Thanks in advance
greets
yehlo

**Comment by plribeiro3000** [comment]
I don't know the specifics about `vsphere` but fog does not support it.
If you find some way to do it through the api we can add it to `fog`.

**Comment by jrgarcia** [comment]
@yehlo I know it's taken a while for me to get back to you. I'm not sure of a way to get that info from `fog-vsphere`, but you may be able to get that info from [RbVmomi](https://rubygems.org/gems/rbvmomi/versions/1.8.2). `fog-vsphere` is actually, for the most part, wrapping that library. I'm not too entirely familiar with it (the majority of `fog-vsphere` was written before I began maintaining it), but it should expose all of the vSphere SDK.
