### ISSUE TITLE
Vmware Customization doesn't (seem to) pick up run-once commands

### ISSUE THREAD

**Issue by finkelamein** [fog/fog-vsphere#37]
see https://groups.google.com/forum/#!topic/foreman-users/ixUzNUJ7dkY
and
http://projects.theforeman.org/issues/14979

I'm trying to pinpoint where to look for the bug.
Sadly i'm mostly blind for the part between rendered template and actual sysprep in the windows client.

**Comment by jrgarcia** [comment]
@finkelamein I'm not familiar with Foreman or Windows, but we do parse the YAML [here](https://github.com/fog/fog-vsphere/blob/abe716059c830d039a90ea77f04efadb0d4daf11/lib/fog/vsphere/requests/compute/cloudinit_to_customspec.rb#L8). It appears the YAML that you mention [here](https://groups.google.com/forum/#!topic/foreman-users/ixUzNUJ7dkY) is an ERB template. I would need to see the rendered YAML to see what's going on in our code. Though, we really don't do anything, but transform the YAML to a `Hash` and pass it on. The underlying problem may actually be in [RbVmomi](https://github.com/vmware/rbvmomi/).

**Comment by finkelamein** [comment]
See attached file, that is the foreman rendered yaml.
[w2k8r2-sysprep.yaml.txt](https://github.com/fog/fog-vsphere/files/297079/w2k8r2-sysprep.yaml.txt)

**Comment by jrgarcia** [comment]
That YAML makes it through `fog-vsphere` just fine. The problem may be in RbVmomi.

**Comment by finkelamein** [comment]
To aid debugging in RbVmomi, can you pastebin the data you pass to RbVmomi?

**Comment by jrgarcia** [comment]
@finkelamein It's a Ruby `Hash` object. You can see the output here: https://gist.github.com/jrgarcia/049d5d7d1c02bd7ba9a607aed817ed8a

**Comment by jrgarcia** [comment]
@finkelamein I'm going to close this for now. However, if you hear *anything* from RbVmomi that leads to you thinking this is occurring inside of fog-vsphere, please don't hesitate to re-open this.
