### ISSUE TITLE
How to specify a cluster when cloning from template

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-vsphere#46]
Hello,

How can I specify which cluster will be the VM cloned into?

My usecase is the following:
I have one datacenter `d1` with two clusters `c1d1` and `c2d1`. I want to create a VM called `m1c2d1` in cluster `c2d1` by cloning from a template `t1c1d1` (yes, the template is hosted on a cluster `c1d1`).

Thanks

Original issue opened by @pdilung at fog/fog#3657

**Comment by plribeiro3000** [comment]
cc/ @geemus @nirvdrum @estonfer

**Comment by jrgarcia** [comment]
@pdilung I wish I could say there was more documentation. I had to dig through the code to find this. I'm hoping to start documenting this as soon is possible. I just haven't had a lot of time lately. Hopefully I'll get some time soon. Here is what I found:

You can pass the cluster through the `clone` options. For example,

```ruby
options = {
  ...
  'resource_pool' => ['cluster_name', 'resource_pool']
}
server.clone(options)
```

This seems unintuitive to me, but that's how it appears to be done. The RDoc for that is [here](https://github.com/fog/fog-vsphere/blob/master/lib/fog/vsphere/requests/compute/vm_clone.rb#L54-L58). Note the comment

> Only works with clusters within same same datacenter as where you're cloning from.

Found from the `clone` method on `Server` model [here](https://github.com/fog/fog-vsphere/blob/master/lib/fog/vsphere/models/compute/server.rb#L125).
