### ISSUE TITLE
Could not descend into . Please check your path. /Datacenters

### ISSUE THREAD

**Issue by chris1984** [fog/fog-vsphere#62]
If you have a top level folder with a data center inside of it we get the following error:

Failed to create a compute VMWare (VMware) instance test.katellolabs.lan: Could not descend into . Please check your path. /Datacenters.

The failing code is:

 | Fog::Compute::Vsphere::NotFound: /Datacenters/Internal/RH_Engineering/TEST/Linux/Sat6_test_template was not found
 | /opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-0.6.3/lib/fog/vsphere/requests/compute/get_virtual_machine.rb:28:in `get_vm_ref'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-0.6.3/lib/fog/vsphere/requests/compute/get_virtual_machine.rb:7:in `get_virtual_machine'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-0.6.3/lib/fog/vsphere/requests/compute/vm_clone.rb:22:in `vm_clone_check_options'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-0.6.3/lib/fog/vsphere/requests/compute/vm_clone.rb:96:in `vm_clone'

The error message we get seems to be coming from: 
/opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-0.6.3/lib/fog/vsphere/requests/compute/get_folder.rb

**Comment by jrgarcia** [comment]
Thanks for reporting! That is a much older version of `fog-vsphere`. I'm not sure that a newer version is going to solve the problem though.

I'll see if I can recreate the issue and provide a fix for that, though if this is through Foreman, I'm not sure that the fix will help you much. In providing a fix, I may be able to find a workaround though.

**Comment by chris1984** [comment]
Thanks for trying to find a work-around. I can find a way around the Foreman piece, if you are able to find a work-around in the code. I will also see if there is a fix about getting a newer version of the gem put into Foreman.

**Comment by chris1984** [comment]
@jrgarcia Happy New Year, did you happen to find a work-around for this issue yet, or are you still looking into it?

**Comment by jrgarcia** [comment]
@chris1984 Thanks! I've been on vacation for a while and just got back. I'll take a look today to see what I can find.

**Comment by jrgarcia** [comment]
@chris1984 I'm sad to say that I've looked into this and while I believe the problem may be in `fog-vsphere`, there doesn't appear to be a way to work around it. I'm going to try and fix this without breaking other users, but that will involve a new release. If anything changes, you'll be the first to know!

**Comment by chris1984** [comment]
@jrgarcia Can I help with this issue, it would be cool to contribute some code to Fog :)

**Comment by jrgarcia** [comment]
👍 By all means
