### ISSUE TITLE
How to run custom startup script/command by customization_spec?

### ISSUE THREAD

**Issue by MiloCheung** [fog/fog-vsphere#65]
Hi all, I'm adding some startup command for windows server by "customization_spec" in vm_clone function. The windows server vm can be launched without any problem, but when I login into the vm, the startup command seem cannot perform. Am I misunderstand the usage of customization_spec?

Thank you very much.

Here's my testing code:
```
    test_options = {
      "name"=>"milotest",
      "server_image"=>"WinSer2012R2",
      "datacenter"=>"datacenter",
      "template_path"=>"WinSer2012R2",
      "numCPUs"=>4,
      "memoryMB"=>8192,
      "host"=>"10.10.0.1",
      "power_on"=>false,
      "customization_spec" => {
        "globalIPSettings" => {"dnsServerList" =>["8.8.8.8"]},
        "identity" => {
          "SysprepText" => {
            "value" => 'Invoke-Expression ((New-Object System.Net.Webclient).DownloadString("https://xxxxx/ConfigureWinRM")); netsh advfirewall firewall add rule name="WinRM_HTTPS" dir=in action=allow protocol=tcp
    lo    #caort=5986 profile=any]'
          }
        }
      }
    }

    clone_vm_result = vsphere_client.vm_clone(test_options)
    server_identifier = clone_vm_result["new_vm"]["id"]
    vm = vsphere_client.servers.get(server_identifier)

    vm.interfaces.each(&:destroy) # cleanup existing interfaces first

    server[:network].each do |n|
      vm.interfaces.create(:network => n[:details][:name], :type => 'VirtualVmxnet3')
    end

    vm.start

```

**Comment by MiloCheung** [comment]
One more question, is it normal practice to config the startup command in vm_clone function? Or the template should be included the startup command/script? Thanks.

**Comment by jrgarcia** [comment]
Hey, sorry it took me so long to respond. I've never seen this usage before so I'm going to have to look into this. I'll see what I can find out. Thanks for reporting this!

**Comment by MiloCheung** [comment]
Thanks @jrgarcia , I also found that there are one more possible params for startup command under vm_clone function(refs: https://github.com/fog/fog-vsphere/blob/master/lib/fog/vsphere/requests/compute/vm_clone.rb). 

The "guiRunOnce" params should be a setting for windows os to run specified command or script, but I also see that there are many required params need to fillin such as "guiUnattended", "identification", "userData",etc. Not sure where can I find out the requested information.

**Comment by jrgarcia** [comment]
Here is the documentation for that object: https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.customization.Sysprep.html#field_detail

**Comment by MiloCheung** [comment]
hi @jrgarcia , finally I figure out how to use the customization_spec. So that I close this ticket. thanks.

**Comment by jrgarcia** [comment]
@MiloCheung Thanks for closing that! I'm glad you got it working, but I feel like that took a lot longer than it should have. Do you have any recommendations on how I can make that easier for people going forward? I want RbVmomi to be as easy as possible to use.
