### ISSUE TITLE
Create Volume Error (The undefined local variable or method `controllerKey')

### ISSUE THREAD

**Issue by MiloCheung** [fog/fog-vsphere#71]
Hi all, the volume.save method will trigger the "The undefined local variable or method `controllerKey'" error. Instead of "controllerKey"(line 64), I only can find a key called "controller_key". Does anyone see this problem? Can we fix it to "self.controller_key = created.controller_key" ? thanks.

fog-vsphere version: 1.7.0
rbvmomi version: 1.9.4

Actual "created" value in volume.save method (file: fog-vsphere/lib/fog/vsphere/models/compute/volume.rb , line: 60):

=>   <Fog::Compute::Vsphere::Volume
  id="6000C295-576f-0e2d-5b70-c778cd108b3a",
  datastore="synology_esx_storage01",
  storage_pod=nil,
  mode="persistent",
  size=10485760,
  thin=true,
  eager_zero=nil,
  name="Hard disk 5",
  filename="[synology_esx_storage01] milotest1/milotest1_4.vmdk",
  size_gb=10,
  key=2004,
  unit_number=4,
  controller_key=1000
>

**Comment by jrgarcia** [comment]
@MiloCheung Thanks for taking the time to report this! I have no problems changing that, but if you put in a pull request for this, you can get the credit for the change. If you'd rather just have me make the change, let me know and I'll do it. I'd just hate to take credit for your help finding, debugging, and reporting. Thanks again!

**Comment by MiloCheung** [comment]
hi @jrgarcia ,I just created a [pull request](https://github.com/fog/fog-vsphere/pull/72) for this case. Please let me know if you need more info on it. Thanks!

**Comment by jrgarcia** [comment]
Closed by #72
