### ISSUE TITLE
Error when cloning vm and adding new volumes

### ISSUE THREAD

**Issue by scambra** [fog/fog-vsphere#77]
I can't add new volumes on clone, maybe I'm doing something wrong, or something else needs to be fixed

My code looks like this:

```ruby
server = client.servers.get(id)
volumes = server.volumes.dup
volumes << server.volumes.new size_gb: size_gb
server.clone ...., volumes: volumes
```
And I get this error:
NoMethodError (undefined method `volumes' for nil:NilClass):
  fog-vsphere (1.7.1) lib/fog/vsphere/models/compute/volume.rb:134:in `calculate_free_unit_number'
  fog-vsphere (1.7.1) lib/fog/vsphere/models/compute/volume.rb:99:in `set_unit_number'

If I add volumes.last.server = server, so new volume has server, I get different error:

```ruby
server = client.servers.get(id)
volumes = server.volumes.dup
volumes << server.volumes.new size_gb: size_gb
volumes.last.server = server
server.clone ...., volumes: volumes
```
And I get this error:

A RbVmomi::Fault occurred in cloud_vms#create:
InvalidController: The device '3' is referring to a nonexisting controller '1,000'.

If I try to copy controller_key from volume in existing vm, it works. Is it right way to do?
```ruby
server = client.servers.get(id)
volumes = server.volumes.dup
volumes << server.volumes.new size_gb: size_gb
volumes.last.server = server
volumes.last.controller_key = volumes[0].controller_key
server.clone ...., volumes: volumes
```

ruby 2.3.1
fog-core 1.43.0
fog-vsphere 1.7.1
rbvmomi 1.9.4

**Comment by jrgarcia** [comment]
I'm not in front of a computer, but I'll take a look as soon as I can.

**Comment by scambra** [comment]
I have it working with the code I post last
