### ISSUE TITLE
suspend vm

### ISSUE THREAD

**Issue by scambra** [fog/fog-vsphere#80]
Add vm_suspend request for SuspendVM_Task, so all energy related tasks of vsphere are supported. There are power on and power off requests, using PowerOffVM_Task and PowerOnVM_Task, and vm reboot request which uses ResetVM_Task or RebootGuest, only SuspendVM_Task missing, if I don't miss other tasks

**Comment by jrgarcia** [comment]
Sorry it took me so long to add this! I'll push a new release with this soon.

**Comment by scambra** [comment]
thanks!
