### ISSUE TITLE
Change connected status of interfaces

### ISSUE THREAD

**Issue by scambra** [fog/fog-vsphere#81]
I would like to change connected status of interfaces in an existing vm. It's possible to change in vcenter, with edit settings for hardware. I don't see how to change it with fog, I read some sdk docs and I didn't find how to do it, but I guess it's possible.

If you give some guiding to do it with RbVmomi, I could give a try and send a pull request

**Comment by jrgarcia** [comment]
I'm actually not sure what's available for that, but I'll check on that and see what's available.

**Comment by jrgarcia** [comment]
I imagine you could use the `ReconfigureVM_Task` on `VirtualMachine` and pass it the changes to the interface. I will test this later today to see if it's possible and how.

**Comment by jrgarcia** [comment]
I just realized there is a `update_vm_interface` method. Would that not handle this?

**Comment by scambra** [comment]
I will give a try

**Comment by scambra** [comment]
I don't think update_vm_interface will change connected flag, it sends deviceChange parameter, with operation edit and device = raw_interface, the only changed in raw_interface is backing, using interface from options argument.

I think it would be nice to have a way to change connectable attribute in raw interface: https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.device.VirtualDevice.ConnectInfo.html

What do you think about accepting connectable hash in options and set values from that hash in connectable class in raw_interface?

```ruby
          if options[:connectable]
            options[:connectable].each do |key, value|
              raw_interface.connectable.send("#{key}=", value)
            end
          end
```

**Comment by jrgarcia** [comment]
I think I'd be ok with that, but I don't really want to make that method bigger. If we could move that logic into a private method that gets called inside `update_vm_interface` that would be great. See `vm_clone` for why continuing to add functionality inline worries me :smile:. Do you want to make a PR for this to get the credit for the work or do you want me to implement it?

**Comment by scambra** [comment]
Ok, I added pull request using a private method, I didn't have chance to test that code
