### ISSUE TITLE
Error when clone VM from template to other cluster

### ISSUE THREAD

**Issue by scornelissen85** [fog/fog-vsphere#95]
I have a template VM, which is located at cluster A. This cluster has it's own datastore cluster. This Cluster consists of several ESX hosts. The template is placed on one of these ESX hosts, and stored on one of the datastores in the datastore cluster, attached to cluster A. 

Next to cluster A I have cluster B, also with it's own datastore cluster and ESX hosts. Both clusters are in the same resource pool, the default "Resources". I want to make a VM on cluster B from the template located at cluster A. When I try to create the VM I get the following error:
`vim.fault.NoCompatibleHost`

This goes wrong, as far as I can see, because it tries with DRS to determine the best datastore of Cluster B. But I think it uses the ESX host where the template is located as host, which is at cluster A. How should it work, should ESX automatically determine the cluster when choosing DRS enabled datastore?

It works when I locate the template on cluster B and then create a VM on cluster B from the template on cluster B. But then I have to keep 2 templates.

Furthermore, I don't know if it's a shortcoming for fog, rbvmomi or the API from vSphere.

**Comment by scornelissen85** [comment]
I see that https://github.com/fog/fog-vsphere/pull/70 fixes my issue. Closing for now.

**Comment by jrgarcia** [comment]
Ok, that PR needs some changes that never got made. I'll accept it later today and make the necessary changes.

**Comment by jrgarcia** [comment]
@scornelissen85 I apologize for not getting to this sooner, but I just released 1.11.2 with #70 included.

**Comment by scornelissen85** [comment]
Thanks.
